//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBook.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EBook.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap addbtn {
            get {
                object obj = ResourceManager.GetObject("addbtn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Hồi 1. TAI HỌA BẤT NGỜ
        ///
        ///Nước sông Tiền Đường mênh mông, ngày đêm vòng qua thôn Ngưu Gia ở Lâm An không ngừng chảy ra biển lớn. Một dãy vài mươi cây bách ven sông lá đỏ như lửa, đang lúc tháng tám. Đồng cỏ quanh thôn đang bắt đầu úa vàng, dưới ánh tà dương càng thêm mấy phần hoang liêu.
        ///Dưới hai gốc tùng lớn có một đám thôn dân, đàn ông đàn bà và khoảng mười mấy đứa trẻ con đang tập trung lắng nghe một ông già gầy gò kể chuyện. Người kể chuyện khoảng năm mươi tuổi, mặc một chiếc trường bào màu xanh cũ đ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ahxd_c1 {
            get {
                return ResourceManager.GetString("ahxd_c1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Hồi 10. Oan gia gặp gỡ
        ///
        ///Hoàn Nhan Khang chợt nhìn thấy Dương Thiết Tâm, sau cơn hoảng sợ lập tức nhận ra, kêu lớn một tiếng:
        ///- A, té ra là ngươi!
        ///Rồi nhấc thương sắt lên đánh ra hai chiêu Hành bộ trừng hổ. Triều thiên nhất trụ hương, mũi thương lóe lên đâm thẳng vào cổ họng Dương Thiết Tâm.
        ///Bao Tích Nhược kêu lên:
        ///- Đây là cha ruột của ngươi, ngươi.., ngươi còn không tin sao?
        ///Rồi ngẩng đầu đập mạnh vào tường, chát một tiếng ngã lăn ra đất.
        ///Hoàn Nhan Khang cả kinh, lùi lại tránh qua, thu thương nhì [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ahxd_c10 {
            get {
                return ResourceManager.GetString("ahxd_c10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Hồi 11. Trường Xuân nhận thua
        ///
        ///Sa Thông Thiên thấy sư đệ nguy hiểm vội tung người vọt qua gạt phát trảo của Mai Siêu Phong. hai người cổ tay chạm nhau đều cùng thấy cánh tay tê chồn. trong lòng hoảng sợ. Lúc ấy bên trái vù vù mấy tiếng. liên châu tiền tiêu của Bành Liên Hổ đã bay tới. Mai Siêu Phong tiện tay nhấc Hầu Thông Hải lên ném về phía ấy. ái cha một tiếng gào lớn. Hầu Thông Hải đã bị loạt tiền đánh vào người. Hoàng Dung giữa lúc hỗn loạn kêu lớn:
        ///- Tam đầu giao, cung hỷ phát tài được bao nhiêu  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ahxd_c11 {
            get {
                return ResourceManager.GetString("ahxd_c11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Hồi 12. Kháng Long hữu hối
        ///
        ///Hoàng Dung đang định xé con gà ra, sau lưng chợt có người nói:
        ///- Xé làm ba. Phần cái phao câu để cho ta!
        ///Hai người giật nảy mình, sau lưng có người lén tới như thế mà mình hoàn toàn không hay biết gì, vội vàng quay lại, chỉ thấy người nói là một người ăn mày trung niên. Người này hàm vuông mặt dài, dưới cằm có râu, tay thô chân to, quần áo trên người vá chằng vá đụp nhưng rất sạch sẽ, cầm một chiếc gậy trúc xanh bóng loáng như ngọc, lưng đeo một chiếc hồ lô lớn sơn đỏ, vẻ m [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ahxd_c12 {
            get {
                return ResourceManager.GetString("ahxd_c12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Hồi 13. Phế nhân ngũ hồ
        ///
        ///Hoàng Dung trở về khách điếm, tự cho rằng mình đã làm một điều tốt, trong lòng rất đắc ý ngủ ngon một đêm, sáng hôm sau kể lại với Quách Tĩnh. Quách Tĩnh vì việc này đã mất rất nhiều sức lực hôm ấy đánh nhau với Hoàn Nhan Khang sứt đầu mẻ trán cũng chỉ vì muốn y thành thân với Mục Niệm Từ, lúc ấy nghe nói hai người bọn họ tình ý hòa hợp cũng rất vui vẻ, càng vui vẻ hơn là từ nay trở đi Khưu Xử Cơ và Giang Nam lục quái không thể ép mình phải cưới Mục Niệm Từ nữa. Hai người trong  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ahxd_c13 {
            get {
                return ResourceManager.GetString("ahxd_c13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Hồi 14. Đảo chủ Đào hoa
        ///
        ///Chỉ thấy năm người đàn ông một người đàn bà bước vào sảnh, chính là Giang Nam lục quái. Họ từ bắc xuống nam, sắp về tới cố hương, hôm ấy đi qua Thái Hồ, chợt có nhân vật giang hồ lên thuyền ân cần tiếp đãi. Lục quái xa quê đã lâu, không rõ tình hình võ lâm hiện tại, lúc ấy cũng không bộc lộ thân phận của mình, chỉ có Chu Thông dùng tiếng lóng giang hồ đối đáp với họ mấy câu. Người lên thuyền vốn là Trương đầu lĩnh thuộc hạ của Quy Vân trang.
        ///Y vâng lệnh Lục Quán Anh ra hồ đón t [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ahxd_c14 {
            get {
                return ResourceManager.GetString("ahxd_c14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Hồi 15. Thần Long bái vĩ
        ///
        ///Lục Quán Anh đỡ Hoàn Nhan Khang dậy, thấy y đã bị điểm trúng huyệt đạo không thể động đậy, chỉ có hai tròng mắt là còn chuyển động. Lục Thừa Phong nói:
        ///- Ta đã đáp ứng sư phụ ngươi thả ngươi đi.
        ///Thấy y bị điểm huyệt không phải là thủ pháp bản môn, tuy mình có thể giải huyệt giúp y nhưng đối với người điểm huyệt thì có chỗ bất kính, đang định cất tiếng hỏi thì Chu Thông đã bước qua búng vào hông Hoàn Nhan Khang mấy cái lại vỗ nhẹ mấy chưởng lên lưng y, giải khai huyệt đạo. Lục [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ahxd_c15 {
            get {
                return ResourceManager.GetString("ahxd_c15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Hồi 16. Cửu âm chân kinh
        ///
        ///Quách Hoàng hai người từ Trình phủ ra về mệt nhọc suốt nửa đêm, đang định về khách điếm nghỉ ngơi, chợt nghe tiếng vó ngựa vang lên, một kỵ mã từ phía nam phóng lên, đang dần dần tới gần đột nhiên dừng lại. Hoàng Dung nghĩ thầm:
        ///- Lại là chuyện gì lạ đây? Chắc cũng nhiệt náo lắm.
        ///Lập tức triển khai khinh công chạy qua định nhìn cho rõ, Quách Tỉnh cũng chạy theo phía sau. Tới gần thì hoàn toàn bất ngờ, chỉ thấy Dương Khang nắm cương ngựa đứng ở cạnh đường trò chuyện với Âu Dươ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ahxd_c16 {
            get {
                return ResourceManager.GetString("ahxd_c16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Hồi 17. Song thủ hổ bác
        ///
        ///Chu Bá Thông nói:
        ///- Ngươi nói là sư ca ta sau khi chết hiển linh à? Hay là hoàn hồn sống lại? Đều không phải đâu, y là giả chết.
        ///Quách Tĩnh a một tiếng nói:
        ///- Giả chết à?
        ///Chu Bá Thông nói:
        ///- Phải rồi. Té ra trước khi sư ca ta chết mấy ngày đã biết Tây độc rình rập gần đó, chỉ cần y chết là sẽ tới cướp kinh thư, nên y dùng nội công thượng thừa bế khí giả chết, nhưng nếu nói cho các đệ tử biết mọi người giả vờ khóc lóc thì cũng không thể giống lắm. Tây độc vô cùng giảo hoạt,  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ahxd_c17 {
            get {
                return ResourceManager.GetString("ahxd_c17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Hồi 18. Ba cái đề thi
        ///
        ///Quách Tĩnh đi theo tiếng bầy rắn, đi được vài mươi bước, dưới ánh trăng quả nhiên thấy hàng ngàn hàng vạn con rắn xanh bày thành hàng dài ngoằn ngoèo tiến lên. Hơn mười hán tử áo trắng tay cầm sào dài khua rắn, không ngừng hất những con rắn ra ngoài vào hàng. Quách Tĩnh giật nảy mình:
        ///- Những người này đem bấy nhiêu rắn tới đây làm gì? Chẳng lẽ là Tây độc tới rồi à?.
        ///Lúc ấy bất kể nguy hiểm, núp sau gốc cây, theo bầy rắn đi lên phía bắc. Đám hán tử xua rắn tựa hồ võ không giỏi l [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ahxd_c18 {
            get {
                return ResourceManager.GetString("ahxd_c18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Hồi 19. Sóng to cá mập
        ///
        ///Hồng Thất công không bao giờ ngờ cuộc thi đọc thuộc lòng sách lại thu được kết quả như thế, so với việc Quách Tỉnh vật Âu Dương Khắc ngã mười bảy mười tám vòng lại còn khiến y kinh ngạc hơn gấp mười, chỉ mừng rỡ cười toét miệng ra không ngậm lại được, nghe Âu Dương Khắc kêu một tiếng như thế, vội hỏi:
        ///- Cái gì? Ngươi không phục à?
        ///Âu Dương Khắc nói:
        ///- Những câu mà Quách huynh đọc so với ghi chép trên kinh văn còn nhiều hơn, nhất định là y đã có Cửu âm chân kinh. Vãn bối lớn mậ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ahxd_c19 {
            get {
                return ResourceManager.GetString("ahxd_c19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Hồi 2. Giang Nam thất quái
        ///
        ///Nhan Liệt bước ra khỏi phòng, chỉ thấy giữa lối đi có một văn sĩ trung niên mang hài da, lẹp kẹp lẹp kẹp thành tiếng nghênh ngang bước tới trước mặt. Văn sĩ này vẻ mặt như cười mà không phải cười, trợn mắt méo miệng, dáng vẻ phờ phạc, toàn thân lấm lem dầu mỡ, áo quần xốc xếch, mặt đầy cáu ghét, xem ra ít nhất cũng hơn mười ngày chưa rửa mặt, cầm một cái quạt giấy rách lem luốc, vừa đi vừa phe phẩy.
        ///Nhan Liệt thấy y rõ ràng là người tư văn mà dáng vẻ lại như thế bất giác cau [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ahxd_c2 {
            get {
                return ResourceManager.GetString("ahxd_c2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Hồi 20. Lén sửa kinh văn
        ///
        ///Hồng Thất công và Quách Tĩnh thấy chú cháu Âu Dương Phong đưa Chu Bá Thông vào khoang sau, liền đi thẳng vào khoang trước thay áo. Bốn cô gái áo trắng bước qua hầu hạ. Hồng Thất công cười nói:
        ///- Lão khiếu hóa trước nay chưa từng được hưởng phúc thế này.
        ///Rồi cởi tuột hết áo quần trên người, một cô gái áo trắng dùng khăn khô lau cho y. Quách Tĩnh mặt đỏ bừng, không dám cởi áo.
        ///Hồng Thất công cười nói:
        ///- Sợ cái gì? Họ ăn thịt ngươi à?
        ///Hai cô gái áo trắng bước lên định cởi già [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ahxd_c20 {
            get {
                return ResourceManager.GetString("ahxd_c20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Hồi 21. Đá nặng ngàn cân
        ///
        ///Âu Dương Phong chỉ thấy trên người nóng ran, ván thuyền dưới chân chấn động rất mạnh, biết chiếc thuyền vỡ này trong chớp mắt sẽ chìm xuống biển, nhưng Hồng Thất công vẫn đánh ráo riết không hề ngơi tay, nếu không thi triển tuyệt chiêu ra sát thủ chỉ e hôm nay khó mà sống sót, ngọn xà trượng trên tay trái chợt rút về, tay phải quét mạnh ra. Hồng Thất công trúc bổng đập lên xà trượng, tay trái vung ra gạt tay y, chợt thấy cánh tay Âu Dương Phong theo thế cong lại, cử quyền mau n [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ahxd_c21 {
            get {
                return ResourceManager.GetString("ahxd_c21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Hồi 22. Cưỡi cá ngao du
        ///
        ///Hoàng Dung thấy Âu Dương Phong lặn ngòi ngoi nước bế cháu lên bờ, khuôn mặt vốn âm trầm cũng đã tươi cười hớn hở nhưng rốt lại cũng không cám ơn mình và Quách Tĩnh một tiếng, lập tức kéo tay áo Quách Tĩnh quay về động đá.
        ///Quách Tĩnh thấy nàng có vẻ lo lắng, bèn hỏi cô đang nghĩ gì thế Hoàng Dung nói:
        ///- Ta đang nghĩ ba chuyện, đều rất khó khăn.
        ///Quách Tĩnh nói:
        ///- Cô thông minh như thế, chắc có cách thôi.
        ///Hoàng Dung cười khẽ một tiếng, qua hồi lâu lại nhướng mày. Hồng Thất côn [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ahxd_c22 {
            get {
                return ResourceManager.GetString("ahxd_c22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Hồi 23. Đại náo cấm cung
        ///
        ///Hồng Thất công, Chu Bá Thông, Quách Tĩnh, Hoàng Dung bốn người lên thuyền nhỏ đi về đất liền phía tây. Quách Tĩnh ngồi ở cuối thuyền chèo, Hoàng Dung thì không ngừng hỏi han Chu Bá Thông về việc cưỡi cá mập ngao du trên biển, Chu Bá Thông cao hứng, lập tức muốn tìm cách bắt cá mập để cùng Hoàng Dung nô đùa một phen.
        ///Quách Tĩnh thấy sắc mặt sư phụ có vẻ không hay, bèn hỏi:
        ///- Lão nhân gia người thấy thế nào?
        ///Hồng Thất công không đáp, thở hổn hển, tiếng nghe khò khè. Sau khi y  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ahxd_c23 {
            get {
                return ResourceManager.GetString("ahxd_c23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Hồi 24. Mật thất trị thương
        ///
        ///Hoàng Dung bước ra ngoài hai bước, quay đầu lại nhìn, chỉ thấy trong ánh mắt Quách Tĩnh hơi lộ vẻ nghi ngờ, nghĩ chắc y nhìn thấy sát khí trên mặt mình, nghĩ thầm:
        ///- Mình giết cô Ngốc không quan trọng, nhưng Tĩnh ca ca khỏe rồi nhất định sẽ cãi nhau với mình một trận.
        ///Lại nghĩ:
        ///- Cãi nhau với mình cũng được, nhưng biết đâu suốt đời y không nói tới chuyện này nhưng trong lòng cứ căm hận cũng rất vô vị. Thôi thôi thôi, chúng ta mạo hiểm chuyến này cho xong.
        ///Lúc ấy bèn đóng [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ahxd_c24 {
            get {
                return ResourceManager.GetString("ahxd_c24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Hồi 25. Quán nhỏ hoang thôn
        ///
        ///Hoàng Dược Sư ngẩng đầu lên trời cười rộ, nói:
        ///- Quán Anh và vị cô nương kia ở lại.
        ///Lục Quán Anh đã biết tổ sư gia tới nhưng thấy y mang mặt nạ, chỉ sợ y không muốn để lộ hành tung, lúc ấy không dám lên tiếng, chỉ cung cung kính kính quỳ xuống dập đầu bốn cái.
        ///Doãn Chí Bình thấy uy thế của Hoàng Dược Sư như thế biết người này không phải tầm thường, khom lưng nói:
        ///- Đệ tử Doãn Chí Bình môn hạ Trường Xuân tử phái Toàn Chân tham kiến tiền bối.
        ///Hoàng Dược Sư nói:
        ///- Mọi ngư [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ahxd_c25 {
            get {
                return ResourceManager.GetString("ahxd_c25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Hồi 26. Thề mới, hẹn cũ
        ///
        ///Hoàng Dược Sư nghĩ không rõ vì sao có trận đánh với Toàn Chân thất tử, càng không rõ đã kết mối thù sâu, đúng là không có lý do gì, thấy Mai Siêu Phong hơi thở yếu dần, nghĩ tới ân oán mấy mươi năm, trong lòng vô cùng thương cảm, nhịn không được chảy nước mắt.
        ///Mai Siêu Phong miệng thoáng nụ cười, vận công lực lần cuối, chát một tiếng, dùng tay phải đánh gãy tay trái, kế đập mạnh tay phải lên tảng đá kê cột nhà, cánh tay lập tức gãy đôi. Hoàng Dược Sư sửng sốt. Mai Siêu Phong nó [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ahxd_c26 {
            get {
                return ResourceManager.GetString("ahxd_c26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Hồi 27. Trước đài hiên viên
        ///
        ///Hai người đang đùa giỡn, tiếng chân lại vang lên ở thang lầu, ba trưởng lão Cái bang vừa theo Dương Khang đi xuống lúc nãy lại trở lên, bước tới cạnh bàn hai người Quách Hoàng làm lễ. Trong đó một người trắng trắng to béo, để một chòm râu bạc, nếu không phải quần áo trên người vá chằng vá đụp thì quả là có dáng vẻ của một đại thân sĩ đại tài chủ, y chưa nói đã cười, quả thật gió xuân đầy mặt, một làn hòa khí, nói:
        ///- Mới rồi lão ăn mày họ Lỗ ngấm ngầm hạ độc thủ với hai vị,  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ahxd_c27 {
            get {
                return ResourceManager.GetString("ahxd_c27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Hồi 28. Trên ngọn thiết chưởng
        ///
        ///Lúc ấy Lỗ Hữu Cước đã tỉnh lại, bốn trưởng lão xúm lại bàn bạc. Lỗ Hữu Cước nói:
        ///- Hiện chân tướng chưa rõ ràng, chúng ta phải hỏi kỹ cả hai bên, quan trọng nhất là tra xét cho ra việc sống chết của Hồng lão bang chủ.
        ///Ba trưởng lão phái áo sạch lại nói:
        ///- Chúng ta đã lập bang chủ, há lại tùy ý thay đổi? Quy củ nhiều đời của bang ta là quyết không được trái lệnh của bang chủ .
        ///Bốn người tranh cãi không thôi. Lỗ Hữu Cước xương ngón tay đều gãy, cắn răng chịu đau, nhưng  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ahxd_c28 {
            get {
                return ResourceManager.GetString("ahxd_c28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Hồi 29. Gái ẩn đầm tối
        ///
        ///Quách Tĩnh trên lưng điêu luôn miệng hò hét, gọi con tiểu hồng mã dưới đất chạy theo, trong chớp mắt đôi điêu đã bay khá xa. Đôi điêu tuy lớn nhưng cõng thêm người trên lưng rốt lại cũng khó bay xa, không bao lâu dần dần không chi trì được càng bay càng thấp, sau cùng hạ xuống đất. Quách Tĩnh nhảy xuống lưng điêu, chạy qua xem Hoàng Dung, thấy nàng nằm hôn mê trên lưng điêu, vội cởi áo buộc nàng ra, giúp nàng đẩy khí huyết lưu thông. Qua một hồi lâu, Hoàng Dung mới dần dần tỉnh l [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ahxd_c29 {
            get {
                return ResourceManager.GetString("ahxd_c29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Hồi 3. Gió cát sa mạc
        ///
        ///Các sư trong chùa thấy Tiêu Mộc viên tịch đều đau thương khóc lóc. Có người băng bó giúp vết thương cho những người bị thương, dìu vào khách xá.
        ///Chợt nghe trong cái vạc đồng dưới cái chuông có tiếng leng keng không dứt, không biết bên trong là quái vật gì các sư ngẩn mặt nhìn nhau, tay chân luống cuống, lúc ấy đồng thanh tụng Cao vương kinh, nào ngờ trong tiếng Cứu khổ cứu nạn. A di đà Phật, cái vạc vẫn không ngừng Khua vang, sau cùng có mười mấy người to gan xúm lại hợp lực dùng [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ahxd_c3 {
            get {
                return ResourceManager.GetString("ahxd_c3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Hồi 30. Nhất Đăng đại sư
        ///
        ///Hai người theo đường núi đi về phía trước, không bao lâu đã tới cuối đường, phía trước là một chiếc cầu đá rộng khoảng một thước bắc qua hai ngọn núi, mây mù bao phủ, nhìn không thấy đầu bên kia. Nếu ở dưới đất thì một con đường nhỏ rộng hơn thước chẳng đáng gì, nhưng chiếc cầu đá này thì bên dưới là vực sâu, đừng nói là đi lại, chỉ nhìn xuống một cái cũng không khỏi tim đập chân run. Hoàng Dung thở dài nói:
        ///- Vị Đoàn Hoàng gia này ở ẩn kín đáo thật, dù ai có thù hận không đội [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ahxd_c30 {
            get {
                return ResourceManager.GetString("ahxd_c30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Hồi 31.  Khăn gấm uyên ương
        ///
        ///Nhất Đăng đại sư hạ giọng thở dài nói:
        ///- Mối họa thật sự là ở ngay ta. Ta là vua nước Đại Lý nhỏ, tuy không như thiên tử Trung Hoa trong hậu cung có ba ngàn người, nhưng số hậu phi cung tần cũng rất đông, ờ, đúng là làm ra tội nghiệt. Nhớ lại ta trước nay hiếu võ, ít gần đàn bà, ngay cả hoàng hậu cũng mấy ngày khó gặp mặt một lần thì các quý phi cung tần khác làm sao còn có ngày được gần gũi?
        ///Nói tới đó nhìn qua bốn người đệ tử nói:
        ///- Lý do bên trong của chuyện này các ng [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ahxd_c31 {
            get {
                return ResourceManager.GetString("ahxd_c31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Hồi 32. Sông to thác hiểm
        ///
        ///Mục Niệm Từ để Hoàng Dung cầm tay phải, y nhìn hoa rơi trên mặt nước, nói:
        ///- Ta thấy y giết Âu Dương Khắc, chỉ cho rằng từ đây y đã cải tà quy chính, lại thấy hai vị cao thủ Cái bang cung cung kính kính đưa y đi, ta vốn có biết hai vị đại thúc Cái bang ấy, biết họ là thuộc hạ thân tín của Hồng Thất công lão nhân gia mà đối xử với y như thế, trong lòng rất mừng rỡ, bèn đi cùng y.
        ///Sau khi ta tới Nhạc Châu, Cái bang mở đại hội ở Quân sơn. Trước đó y đã nói riêng với ta Hồng ân  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ahxd_c32 {
            get {
                return ResourceManager.GetString("ahxd_c32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Hồi 33. Nạn lớn ngày sau
        ///
        ///Quách Tĩnh và Hoàng Dung lúc ấy trong lòng sung sướng, vốn không muốn dính vào chuyện không đâu, nhưng nghe thấy ba chữ Lão Ngoan đồng đều giật nảy mình, cùng nhảy vọt lên đuổi mau theo. Hai người phía trước võ công bình thường, vẫn chưa hay biết. Ra khỏi trấn lại chạy thêm năm sáu dặm, hai người kia quanh qua một chỗ vách núi, chỉ nghe tiếng quát tháo chửi mắng không ngừng từ sau núi vang ra.
        ///Quách Hoàng hai người gia tăng cước bộ, quanh qua góc núi, chỉ thấy một đám người đa [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ahxd_c33 {
            get {
                return ResourceManager.GetString("ahxd_c33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Hồi 34. Biến cố trên đảo
        ///
        ///Hoàng Dung múa đến lúc gấp đột nhiên ồ một tiếng ngồi xổm xuống dưới gốc cây, giơ tay vẫy vẫy Quách Tĩnh, sãi chân chạy mau vào rừng. Quách Tĩnh sợ lạc đường, theo sát phía sau, không dám tụt lại nửa bước. Hoàng Dung chạy vòng qua vòng lại một lúc chợt dừng lại chỉ vào một đống gì đó dưới đất hỏi:
        ///- Cái gì thế này?
        ///Quách Tĩnh bước tới mấy bước, chỉ thấy một con ngựa vàng ngã lăn trên mặt đất, vội cúi xuống nhìn kỹ, nhận ra là con ngựa vàng của Tam sư phụ Hàn Bảo Câu vẫn cười, [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ahxd_c34 {
            get {
                return ResourceManager.GetString("ahxd_c34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Hồi 35. Trong miếu thiết thương
        ///
        ///Thuyền vừa cập bến, hai ba mươi người bước lên, bọn Bành Liên Hổ, sa Thông Thiên đều có trong đó. Hai người lên bờ cuối cùng một cao một thấp, người cao là Triệu vương Hoàn Nhan Hồng Liệt nước Đại Kim, người thấp là bang chủ Thiết chưởng bang Cừu Thiên Nhận. Xem ra Hoàn Nhan Hồng Liệt cậy có Âu Dương Phong, Cừu Thiên Nhận hai người xuất mã, lần tỷ võ này chỉ thắng chứ không có bại nên ngang nhiên đích thân trở lại Giang Nam.
        ///Hoàng Dung chỉ Cừu Thiên Nhận nói:
        ///- Cha, co [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ahxd_c35 {
            get {
                return ResourceManager.GetString("ahxd_c35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Hồi 36. Đại quân Tây chinh
        ///
        ///Hoàng Dung buồn bã nói:
        ///- Âu Dương bá bá khen ta nhiều quá. Hiện Quách Tĩnh đã trúng kế của ngươi, không đội trời chung với cha ta. Đợi ngày mai ngươi đi cứu cha ta, nếu cháu ngươi còn sống, ờ, thì chuyện hôn nhân hôm trước, chẳng lẽ lại không nhắc lại được sao?
        ///Âu Dương Phong trong lòng hoảng sợ:
        ///- Y thị đột nhiên nhắc tới chuyện ấy là có dụng ý gì?
        ///Chợt nghe Hoàng Dung nói:
        ///- Cô Ngốc, vị hảo huynh đệ này đối đãi với ngươi rất tốt phải không?
        ///Cô Ngốc nói:
        ///- Đúng thế,  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ahxd_c36 {
            get {
                return ResourceManager.GetString("ahxd_c36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Hồi 37. Trên trời rơi xuống
        ///
        ///Một hôm Quách Tĩnh đóng quân cạnh Na Mật Hà, buổi tối đang trong trướng đọc binh thư, chợt nghe ngoài trướng có một tiếng chát nhỏ vang lên, cửa trướng mở ra, một người bước vào. Đám vệ binh trước trướng bước ra quát tháo ngăn lại, bị người đó khẽ vung tay nhất nhất điểm ngã. Người ấy ngẩng đầu lên cười, dưới ánh đèn nhìn thấy rất rõ, chính là Tây độc Âu Dương Phong. Quách Tĩnh cách Trung thổ hàng vạn dặm, không ngờ ở nơi tha hương tuyệt vực này lại gặp y, bất giác mừng sợ x [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ahxd_c37 {
            get {
                return ResourceManager.GetString("ahxd_c37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Hồi 4. Hắc phong song sát
        ///
        /// Hàn Tiểu Oanh sải chân chạy mau về phía Đông bắc, khom người nhìn qua một cái rồi lập tức chạy trở lại, nói:
        ///- Bên đó mỗi đống có bảy cái, đều là đầu người chết, thịt còn chưa rã hết.
        ///Kha Trấn ác hạ giọng nói:
        ///- Vậy thì họ sẽ tới ngay bây giờ!
        /// Rồi đưa cái đầu lâu cho Toàn Kim Phát, nói:
        ///- Cẩn thận để vào chỗ cũ, đừng để họ thấy có dấu vết bị di động.
        ///Toàn Kim Phát để xong đầu lâu vào chỗ cũ quay lại cạnh Kha Trấn ác. Sáu anh em ngơ ngác nhìn đại ca, chờ y giải thích.
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ahxd_c4 {
            get {
                return ResourceManager.GetString("ahxd_c4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Hồi 5. Cung loan bắn điêu
        ///
        ///Đoàn người xuống khỏi gò, đi không bao lâu chợt nghe phía trước có tiếng thú dữ gầm rít từng hồi từng hồi vang tới. Hàn Bảo Câu kéo cương thúc ngựa phóng về phía trước, được một lúc chợt con hoàng mã đứng lại, thúc thế nào cũng bất động. Hàn Bảo Câu biết có chuyện lạ bèn nhìn ra xa, chỉ thấy trước mặt có một đám người xúm thành vòng tròn, có mấy con báo săn đang cắn xé vật gì đó trên mặt đất. Y biết con ngựa sợ báo, bèn nhảy xuống ngựa rút ngọn Kim long tiên ra cầm ở tay bước  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ahxd_c5 {
            get {
                return ResourceManager.GetString("ahxd_c5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Hồi 6. Nghi trận đầu non
        ///
        ///Trong trướng, lục quái hạ giọng bàn bạc. Hàn Tiểu Oanh nói:
        ///- Người ấy truyền thụ nội công thượng thặng cho Tĩnh nhi, dĩ nhiên không có ác ý.
        ///Toàn Kim Phát nói:
        ///- Nhưng sao y không muốn chúng ta biết? Mà sao lại không nói rõ cho Tĩnh nhi biết đó là nội công?
        ///Chu Thông nói:
        ///- E là người mà chúng ta quen.
        ///Hàn Tiểu Oanh nói:
        ///- Quen à? Vậy thì nếu không phải bạn bè ắt là địch nhân.
        ///Toàn Kim Phát trầm ngâm nói:
        ///- Trong các bạn bè mà chúng ta quen không ai có nội công cao mi [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ahxd_c6 {
            get {
                return ResourceManager.GetString("ahxd_c6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Hồi 7. Tỉ võ chiêu thân
        ///
        ///Giang Nam lục quái và Quách Tĩnh ngày đi đêm nghỉ tiến về phía đông nam, đường đi không phải một ngày, qua khỏi vùng sa mạc thảo nguyên.
        ///Hôm ấy còn cách Trương Gia Khẩu không xa. Quách Tĩnh lần đầu đặt chân tới Trung thổ, cảnh vật đều khác với bình sinh vẫn thấy, trong lòng rất khoan khoái, kẹp chặt hai đùi giục ngựa phi mau, chỉ thấy bên tai gió lộng vù vù, nhà cửa cây cối không ngừng chạy ngược lại phía sau. Đến lúc con tiểu hồng mã chạy một hơi tới cạnh sông Hắc Thủy y mới d [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ahxd_c7 {
            get {
                return ResourceManager.GetString("ahxd_c7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Hồi 8. Chứng tỏ bản lĩnh
        ///
        ///Vương Xử Nhất cước bộ rất mau, không bao lâu đã ra tới ngoài thành, lại chạy thêm vài dặm, tới phía sau một ngọn núi. Y không ngừng gia tăng cước bộ, có ý muốn dò xét võ công của Quách Tĩnh, càng lúc càng chạy mau. Quách Tĩnh ngày trước theo Đan Dương tử Mã Ngọc học công phu thổ nạp, trong hai năm đêm nào cứng lên xuống dốc núi dựng đứng, nên lúc ấy chạy mau một hồi, tuy vừa ác đấu xong nhưng vẫn chi trì được. Gió mạnh quét tuyết vào mặt. Vương Xử Nhất chạy ra phía sau một ngọn [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ahxd_c8 {
            get {
                return ResourceManager.GetString("ahxd_c8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Hồi 9. Thương sắt cày hư
        ///
        ///Quách Hoàng hai người tới hậu viện Triệu Vương phủ, vượt tường vào trong. Hoàng Dung dịu dàng nói:
        ///- Công phu khinh công của ngươi cao cường thật!
        /// Quách Tĩnh đang nằm phục dưới chân tường nghe ngóng động tĩnh trong hậu viện, nghe nàng nói thế, trong lòng chợt thấy sung sướng êm đềm không sao tả được.
        ///Qua một lúc, chợt nghe tiếng bước chân, hai người vừa nói vừa cười đi tới, chỉ nghe một người nói:
        ///- Tiểu vương gia nhốt vị cô nương ấy ở đây, ngươi đoán là để làm gì nào?
        ///Ng [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ahxd_c9 {
            get {
                return ResourceManager.GetString("ahxd_c9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ahxd_cover {
            get {
                object obj = ResourceManager.GetObject("ahxd_cover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 37.
        /// </summary>
        public static string ahxd_info {
            get {
                return ResourceManager.GetString("ahxd_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap close1 {
            get {
                object obj = ResourceManager.GetObject("close1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap close2 {
            get {
                object obj = ResourceManager.GetObject("close2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap closee {
            get {
                object obj = ResourceManager.GetObject("closee", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap homebtn {
            get {
                object obj = ResourceManager.GetObject("homebtn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap homebtn1 {
            get {
                object obj = ResourceManager.GetObject("homebtn1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ic_search {
            get {
                object obj = ResourceManager.GetObject("ic_search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ic_search1 {
            get {
                object obj = ResourceManager.GetObject("ic_search1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap kripto_search_b {
            get {
                object obj = ResourceManager.GetObject("kripto-search-b", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap kripto_search_next2 {
            get {
                object obj = ResourceManager.GetObject("kripto_search_next2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap listFavor {
            get {
                object obj = ResourceManager.GetObject("listFavor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap listTruyen {
            get {
                object obj = ResourceManager.GetObject("listTruyen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap listTruyen2 {
            get {
                object obj = ResourceManager.GetObject("listTruyen2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap listTruyen2Xoay {
            get {
                object obj = ResourceManager.GetObject("listTruyen2Xoay", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap maximize {
            get {
                object obj = ResourceManager.GetObject("maximize", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap minium {
            get {
                object obj = ResourceManager.GetObject("minium", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap more {
            get {
                object obj = ResourceManager.GetObject("more", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap small {
            get {
                object obj = ResourceManager.GetObject("small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap smallBCC_CLASS_HOME_05 {
            get {
                object obj = ResourceManager.GetObject("smallBCC-CLASS-HOME-05", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap star {
            get {
                object obj = ResourceManager.GetObject("star", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap starborder {
            get {
                object obj = ResourceManager.GetObject("starborder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap starborder1 {
            get {
                object obj = ResourceManager.GetObject("starborder1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap subbtn {
            get {
                object obj = ResourceManager.GetObject("subbtn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
